// This question is asked by Google. 
// You are given two strings, s and t which only consist of lowercase letters. 
// t is generated by shuffling the letters in s 
// as well as potentially adding an additional random character. 
// Return the letter that was randomly added to t if it exists, otherwise, return ’  ‘.
// Note: You may assume that at most one additional character can be added to t.

// Ex: Given the following strings...

// s = "foobar", t = "barfoot", return 't'
// s = "ide", t = "idea", return 'a'
// s = "coding", t "ingcod", return ''

const potentiallyRandomCharacterInAnagram = (base, baseExtraChar) => {
    let extraLastIndex = base.length;
    let lastIndex = extraLastIndex - 1;
    
    for (let i = 0; i < extraLastIndex / 2; i++) {
      if (base[i] !== baseExtraChar[i])      
        return baseExtraChar[i];
      
      if (base[lastIndex - i] !== baseExtraChar[extraLastIndex - i])
        return baseExtraChar[extraLastIndex - i];
          
    }
    return false;
  }

const s = "coding"
const t = "ingcod"
console.log(`For params "${s}" and "${t}" potentiallyRandomCharacterInAnagram() return : ${potentiallyRandomCharacterInAnagram(s, t)}`);